export const profile = {
  name: 'Mohamad Ammar',
  fullName: 'Mohamad Ammar Mohamad Hassan',
  title: 'AI Engineering | Applied AI & Full-Stack Systems',
  email: 'mohamedammar6650@gmail.com',
  linkedin: 'https://www.linkedin.com/in/mohamad-ammar-898825338/',
  github: 'https://github.com/mohamadammar21-0518',
  location: 'Malaysia',
  cgpa: '3.76 / 4.00',
}

export const projects = [
  {
    name: 'AI Employee · Inbound Revenue Command Center', slug: 'ai-employee-revenue-command-center',
    displayName: 'AI Employee',
    gallery: [
      { image: 'ai-employee-operators.png', alt: 'Supervity Auto operator list showing specialist revenue workflow operators', caption: 'Specialist operators in Supervity Auto' },
      { image: 'ai-employee-command-center.png', alt: 'Autopilot command center dashboard for inbound revenue workflows', caption: 'Inbound revenue command center' },
      { image: 'ai-employee-hackathon-certificate.png', alt: 'Supervity AutoPilot Asia Hackathon certificate of participation', caption: 'AutoPilot Asia Hackathon · Certificate of participation' },
    ],
    problem: 'Revenue automation needs coordinated agents with policy controls and human escalation.',
    contribution: 'Designed the orchestrator, specialist operators, policy checks, exception routing, and backend-connected command centre.',
    outcome: 'A hackathon system coordinating five or more AI operators with human review across revenue workflows.',
    highlight: '5+ AI operators · Governed workflows',
 category: 'AI & data',
    status: 'Autopilot Asia Hackathon · Sales Intelligence', date: 'Jul–Aug 2026',
    repoUrl: 'https://github.com/mohamadammar21-0518/AutoPilot-Round2', liveUrl: null,
    tags: ['Supervity Auto', 'Python', 'FastAPI', 'Next.js', 'PostgreSQL', 'Docker'], image: 'supervity.png', alt: 'Supervity AI logo',
    description: 'A governed AI revenue-capture system designed to coordinate specialist agents while keeping people in control.',
    overview: 'Developed for the Sales Intelligence track at Autopilot Asia Hackathon 2026 using Supervity Auto, Python, FastAPI, PostgreSQL, Next.js, and Docker. The orchestrator coordinates five or more specialist AI operators across revenue workflows, with policy checks, human review, and exception handling for lead matching, intent-based outreach, consent conflicts, and territory allocation. A live command centre connects through the FastAPI backend.',
    focus: 'Observable multi-agent workflows, policy controls, human oversight, and exception routing',
  },
  {
    name: 'DocMind AI · Document Q&A', slug: 'docmind-ai',
    displayName: 'DocMind AI',
    gallery: [
      { image: 'docmind-ragas-evaluation.png', alt: 'DocMind AI retrieval evaluation screen with faithfulness, answer relevance, and context precision metrics', caption: 'RAGAS retrieval evaluation' },
      { image: 'docmind-insights-dashboard.png', alt: 'DocMind AI insights dashboard showing indexed document and retrieval pipeline details', caption: 'Document insights and retrieval pipeline' },
      { image: 'docmind-chat-upload.png', alt: 'DocMind AI chat screen prompting the user to upload a PDF', caption: 'Document Q&A workspace' },
    ],
    problem: 'Readers need answers traceable to the source passages across uploaded PDFs.',
    contribution: 'Built and deployed the RAG application, hybrid retrieval, reranking, streaming, and voice features.',
    outcome: 'Deployed document Q&A with page-level citations and confidence scores; retrieval evaluated with RAGAS.',
    highlight: 'Deployed RAG · Page-level citations',
 category: 'AI & data',
    status: 'Selected project', date: 'May–Jul 2026',
    repoUrl: 'https://github.com/mohamadammar21-0518/DocMind-AI', liveUrl: 'https://docmind-frontend-817865882900.us-central1.run.app',
    tags: ['RAG', 'FastAPI', 'ChromaDB', 'Google Cloud Run'], image: 'docmind.png', alt: 'Original DocMind AI project logo',
    description: 'A deployed document Q&A application that turns uploaded PDFs into a searchable, conversational knowledge source.',
    overview: 'The full-stack RAG system answers questions about one or more PDFs with page-level citations, confidence scores, and streaming responses. Its hybrid retrieval pipeline combines BM25 keyword search (40%) and ChromaDB vector similarity (60%), followed by LLM reranking. Retrieval quality was evaluated with RAGAS; the app also includes voice input and text-to-speech.',
    focus: 'Hybrid retrieval, grounded answers, retrieval evaluation, and a deployed AI product',
  },
  {
    name: 'LocalVoice CRM', slug: 'localvoice-crm',
    displayName: 'LocalVoice CRM',
    gallery: [],
    problem: 'Voice-driven CRM updates need privacy and review before changing records.',
    contribution: 'Building local Whisper.cpp and Ollama processing with editable proposals and approval before database writes.',
    outcome: 'The ongoing build supports up to five chained actions per utterance; optional HubSpot sync remains planned.',
    highlight: 'Up to 5 actions · Human approval',
 category: 'AI & data',
    status: 'In progress', date: '2026', repoUrl: null, liveUrl: null,
    tags: ['Node.js', 'tRPC', 'Whisper.cpp', 'Ollama'], image: 'localvoice-photo.jpg', alt: 'LocalVoice CRM voice workflow illustration',
    description: 'A privacy-first, self-hosted CRM that turns spoken instructions into reviewable proposed actions.',
    overview: 'A local Whisper.cpp speech-to-text and Ollama language-model pipeline converts voice commands into structured CRM actions, supporting up to five chained actions per utterance. Every database write requires human approval; transcripts and editable proposals make the workflow reviewable. Optional HubSpot sync is planned while preserving zero-cloud, offline operation.',
    focus: 'Local voice AI, privacy-first architecture, and approval before data changes',
  },
  {
    name: 'AI-Powered Student Success & Early Intervention Platform', slug: 'student-success-platform',
    displayName: 'Student Success AI',
    gallery: [
      { image: 'student-success-pipeline.jpg', alt: 'Four-step student success workflow: collect, clean, analyze, and display learning engagement signals', caption: 'Four-step data workflow' },
      { image: 'student-success-dashboard-redacted.jpg', alt: 'Student engagement dashboard with identifying details obscured', caption: 'Advisor dashboard · Student details redacted' },
    ],
    problem: 'Advisors need explainable risk signals before deciding how to support students.',
    contribution: 'Designing the weekly data pipeline, XGBoost and SHAP models, and advisor review workflows.',
    outcome: 'In development: an auditable intervention workflow with role-based access.',
    highlight: 'Weekly review cycle · In development',
 category: 'AI & data',
    status: 'Final year project · In progress', date: '2026', repoUrl: null, liveUrl: null,
    tags: ['XGBoost', 'SHAP', 'FastAPI', 'PostgreSQL'], image: 'student-success-photo.jpg', alt: 'Student success analytics illustration',
    description: 'A weekly-cycle early-intervention platform designed to help advisors review student risk signals and act with context.',
    overview: 'The final-year project connects data ingestion, XGBoost risk modelling, SHAP explanations, decision rules, and advisor-facing workflows in a weekly cycle. Its FastAPI and PostgreSQL architecture is planned for Google Cloud Run, with separate student, advisor, and administrator access. Recommendations are designed to stay auditable and subject to advisor review.',
    focus: 'Explainable risk modelling, role-based access, and human-reviewed student support',
  },
  {
    name: 'AquaSense · AI Water Monitoring', slug: 'aquasense',
    displayName: 'AquaSense',
    gallery: [
      { image: 'aquasense-device-concept.jpg', alt: 'Annotated concept render of a water monitoring device with LoRaMesh antenna, Raspberry Pi, camera, and colorimetric strip', caption: 'Water monitoring device concept' },
    ],
    problem: 'Accessible water monitoring needs practical analysis and resilient field communication.',
    contribution: 'Leading software development for AI-assisted colorimetric analysis and LoRaMesh communication.',
    outcome: 'Ongoing sustainability project with Team AquaSense, recognised as a Hult Prize national-level finalist.',
    highlight: 'Software Lead · Hult Prize finalist',
 category: 'AI & data',
    status: 'Software Lead · Hult Prize National Finalist', date: '2025–Present', repoUrl: null, liveUrl: null,
    tags: ['Colorimetric AI', 'LoRaMesh', 'Sustainability'], image: 'aquasense-cover.jpg', alt: 'AquaSense water monitoring environment',
    description: 'An AI-driven colorimetric analysis project developed for the Hult Prize to make water-quality insights more accessible.',
    overview: 'As Software Lead, I guide AI-assisted analysis workflows and LoRaMesh communication protocols, helping build a resilient foundation for field-ready sustainability monitoring. Team AquaSense was a national-level finalist in the Hult Prize AIU 2025/26 Inter-University Competition.',
    focus: 'AI-assisted water analysis, connected systems, and sustainability technology',
  },
  {
    name: 'TDM Insight · Vancomycin Monitoring', slug: 'tdm-insight',
    displayName: 'VancoTrack · TDM Insight',
    gallery: [
      { image: 'vancotrack-splash-screen.jpg', alt: 'VancoTrack vancomycin therapeutic drug monitoring app start screen', caption: 'Application start screen' },
      { image: 'vancotrack-input-workflow.jpg', alt: 'VancoTrack patient and medication data entry workflow', caption: 'Patient and medication inputs' },
      { image: 'vancotrack-results-screen.jpg', alt: 'VancoTrack vancomycin pharmacokinetic result screen with calculated outputs and review notes', caption: 'Calculation results and review notes' },
    ],
    problem: 'Pharmacy calculations need transparent steps and careful input review.',
    contribution: 'Developed the Android app, pharmacokinetic engine, on-device OCR, record history, and PDF export.',
    outcome: 'Three calculation workflows with 30+ validation rules, history for 20 records, and two-page PDF reports.',
    highlight: '3 workflows · 30+ validation rules',
 category: 'Apps & mobile',
    status: 'Selected project', date: '2025–2026',
    repoUrl: 'https://github.com/mohamadammar21-0518/vancotrack', liveUrl: null,
    tags: ['Kotlin', 'Jetpack Compose', 'CameraX', 'ML Kit OCR'], image: 'tdm-app.jpg', alt: 'Actual TDM Insight Android application screenshot',
    description: 'A native Android therapeutic drug monitoring calculator for hospital pharmacy workflows.',
    overview: 'TDM Insight supports pre-dose, post-dose, and pre/post-dose Vancomycin workflows. Its standalone pharmacokinetic engine shows step-by-step values for Ke, half-life, Vd, clearance, trough, and AUC24, supported by more than 30 validation rules. On-device OCR assists with laboratory reports, with mandatory user review, local history for 20 records, and two-page PDF export and sharing.',
    focus: 'Clinical calculations, explainable results, on-device OCR, and validated mobile workflows',
  },
  {
    name: 'Kafe Eman · Multi-Branch Café Platform', slug: 'kafe-eman',
    displayName: 'Kafe Eman',
    gallery: [],
    problem: 'Customers and staff need consistent café workflows across branches.',
    contribution: 'Building menus, reservations, loyalty, authentication, and admin-reviewed feedback.',
    outcome: 'In development: connected customer and staff workflows. AI assistance and order notifications remain planned.',
    highlight: 'Multi-branch workflows · In development',
 category: 'Web & product',
    status: 'In progress', date: '2026', repoUrl: null, liveUrl: null,
    tags: ['React', 'TypeScript', 'Convex', 'Clerk', 'Framer Motion'], image: 'kafe-eman-photo.jpg', alt: 'Kafe Eman café platform illustration',
    description: 'A multi-branch café platform bringing menus, reservations, customer journeys, and staff tools together.',
    overview: 'The platform is being built around public menus and reservations, customer checkout and loyalty workflows, and an administrative dashboard. Customer and staff authentication use separate flows with Clerk and a local admin login; customer feedback passes through admin review before publication. A Groq-orchestrated AI assistant and Twilio/Vapi-based order notifications are planned next.',
    focus: 'Multi-branch product design, customer and staff workflows, and staged AI integrations',
  },
  {
    name: 'AI vs. Cricket · T20 World Cup Predictor', slug: 't20-world-cup-ai',
    displayName: 'T20 World Cup Predictor',
    gallery: [
      { image: 't20-super-eight-predictions.png', alt: 'T20 World Cup Predictor Super Eight group match results and points tables', caption: 'Super Eight stage predictions' },
      { image: 't20-knockout-predictions.png', alt: 'T20 World Cup Predictor semifinal and final projections', caption: 'Knockout stage projections' },
    ],
    problem: 'Match predictions need team performance, recent form, and venue context.',
    contribution: 'Developed the XGBoost pipeline and interactive Streamlit tournament simulation.',
    outcome: 'An application presenting match-win probabilities and simulations from group stage to final.',
    highlight: 'Match probabilities · Tournament simulation',
 category: 'AI & data',
    status: 'Selected project', date: 'Feb 2026',
    repoUrl: 'https://github.com/mohamadammar21-0518/2026-t20-world-cup-prediction', liveUrl: 'https://t20-worldcup-predictor.streamlit.app',
    tags: ['Python', 'XGBoost', 'Streamlit', 'Sports analytics'], image: 't20-predictor-photo.jpg', alt: 'Generated representative photograph of a cricket stadium, bat, and ball',
    description: 'An interactive cricket intelligence dashboard that predicts match outcomes and simulates the tournament through the final.',
    overview: 'An XGBoost model trained on historical T20I data is paired with a four-tier team model. The system accounts for team strength, ICC ratings, venue history, recent form, and the statistical gap between top-ranked teams and underdogs. The Streamlit app presents win probabilities, points-table tracking, automated Super 8 groups, and knockout-stage projections.',
    focus: 'End-to-end modelling, domain-aware features, and interactive tournament simulation',
  },
]

export const capabilities = [
  { title: 'Programming', description: 'Python, SQL, C, Kotlin, TypeScript, and JavaScript for data, application, and mobile development.', tags: ['Python', 'SQL', 'Kotlin', 'TypeScript', 'JavaScript', 'C'], glyph: '⌘', images: ['t20-predictor-photo.jpg', 'tdm-app.jpg', 'docmind.png'] },
  { title: 'Data & Machine Learning', description: 'From data processing and feature engineering through model development, evaluation, and clear visual analysis.', tags: ['XGBoost', 'scikit-learn', 'SHAP', 'Data analysis', 'Visualization'], glyph: '✳', images: ['t20-predictor-photo.jpg', 'student-success-photo.jpg', 'supervity.png'] },
  { title: 'AI Systems', description: 'Building retrieval and language-model applications with hybrid search, multi-agent workflows, voice AI, and human review.', tags: ['RAG', 'Hybrid retrieval', 'Multi-agent', 'Voice AI', 'Human-in-the-loop'], glyph: '✦', images: ['docmind.png', 'localvoice-photo.jpg', 'supervity.png'] },
  { title: 'Web & Backend', description: 'Creating full-stack products and APIs with modern React frameworks, typed services, and backend systems.', tags: ['React', 'Vite', 'Next.js', 'FastAPI', 'Django REST', 'Node.js', 'tRPC', 'MERN'], glyph: '↗', images: ['kafe-eman-photo.jpg', 'localvoice-photo.jpg', 'supervity.png'] },
  { title: 'Mobile Development', description: 'Native Android interfaces and tested application flows, including camera-assisted input and on-device OCR.', tags: ['Jetpack Compose', 'MVVM', 'CameraX', 'ML Kit OCR'], glyph: '▣', images: ['tdm-app.jpg', 'docmind.png', 'student-success-photo.jpg'] },
  { title: 'Data & Cloud', description: 'Relational and vector data stores, containerized applications, and cloud deployment foundations.', tags: ['PostgreSQL', 'MySQL', 'ChromaDB', 'Google Cloud Run', 'Docker'], glyph: '☁', images: ['docmind.png', 'supervity.png', 'student-success-photo.jpg'] },
]

export const education = [
  { title: 'Bachelor of Data Science', institution: 'Universiti Antarabangsa Albukhary (AIU) · Malaysia', date: 'Oct 2024 – Oct 2027', detail: 'Current CGPA: 3.76 / 4.00. Relevant coursework includes Data Processing, Machine Learning, Database Systems, and Full-Stack Development.' },
  { title: 'Foundation in Computing', institution: 'Universiti Antarabangsa Albukhary (AIU) · Malaysia', date: 'Oct 2023 – Oct 2024', detail: 'Built the computing foundation leading into undergraduate data science and software development.' },
]

export const experience = [
  { title: 'Software Lead · AquaSense', organization: 'Hult Prize project · National finalist', date: '2025 – Present', detail: 'Leading development of AI-driven colorimetric analysis and LoRaMesh communication protocols for water-quality monitoring.' },
  { title: 'Student Mentor', organization: 'Kedah Maker Fair · Young Innovators Challenge', date: 'Aug 2025', detail: 'Mentored 66 teams from 20 schools developing AI-for-social-good prototypes in healthcare, education, and sustainability. Completed the Train the Trainer Workshop by Chumbaka Sdn Bhd.' },
  { title: 'Project Facilitator', organization: 'Net Zero Carbon Emission for Youth Leaders Programme', date: 'Mar 2024', detail: 'Coordinated youth engagement activities and workshops focused on sustainability, carbon neutrality, and climate action.' },
]

export const credentials = {
  certifications: ['Google Cloud · Cloud Computing Fundamentals', 'Python Programming', 'Machine Learning Fundamentals'],
  training: ['Full MERN Stack Bootcamp', 'Django REST Bootcamp', 'Modern Web Development Workshop · Frontend Edition', 'Train the Trainer Workshop'],
  activities: ['Treasurer · Sri Lankan Student Community', 'CNL Leadership Development Programme', 'University Sports'],
  strengths: ['Problem solving', 'Technical communication', 'Leadership', 'Mentorship', 'Collaboration'],
  languages: ['Tamil · Native', 'English · Fluent'],
  interests: ['Football', 'Cricket', 'Frisbee', 'Badminton', 'Competitive programming'],
}

export const questions = [
  ['Are you available for internships or freelance work?', 'Yes. I am seeking internships in AI engineering and Applied AI, and I am open to freelance AI and full-stack development projects. Email me to discuss the scope, timing, and fit.'],
  ['What are you studying?', 'I am completing a Bachelor of Data Science at Universiti Antarabangsa Albukhary (AIU), Malaysia. My current CGPA is 3.76 / 4.00.'],
  ['What are you building now?', 'My current projects are an explainable student-success and early-intervention platform, the Kafe Eman multi-branch café platform, and LocalVoice CRM, a privacy-first voice-driven CRM.'],
  ['What areas do you build in?', 'My career direction is AI engineering: building retrieval systems, language-model applications, voice AI, multi-agent workflows, and explainable machine learning, supported by backend, cloud, web, and mobile engineering.'],
  ['How do you approach responsible AI?', 'I build in clear explanations and human review. For example, my student-success platform pairs model risk signals with SHAP explanations and advisor-reviewed decision rules.'],
  ['What experience do you have mentoring?', 'At the Kedah Maker Fair Young Innovators Challenge, I mentored 66 teams from 20 schools developing AI-for-social-good prototypes.'],
  ['What is the best way to reach you?', 'Email me at mohamedammar6650@gmail.com or connect on LinkedIn.'],
]

